### ISSUE TITLE
Add option in `build.yaml` for `json_serializable`

### ISSUE THREAD

**Issue by myConsciousness** [twitter-dart/twitter-api-v2#272]
# 1. What could be improved

```yaml
targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: true
          checked: true
          create_to_json: true
          field_rename: snake
          explicit_to_json: true # ← Add this line

      # The end-user of a builder which applies "source_gen|combining_builder"
      # may configure the builder to ignore specific lints for their project
      source_gen|combining_builder:
        options:
          ignore_for_file:
          - non_constant_identifier_names
```
# 2. Why should this be improved

# 3. Any risks?

# 4. More information
