### ISSUE TITLE
INFO: The annotation 'JsonKey' can only be used on fields or getters

### ISSUE THREAD

**Issue by myConsciousness** [twitter-dart/twitter-api-v2#42]
# 1. What could be improved

<img width="820" alt="スクリーンショット 2022-05-01 17 40 29" src="https://user-images.githubusercontent.com/13072231/166138635-51835f17-ac79-407b-9e93-8cc6d87cde6d.png">

# 2. Why should this be improved

# 3. Any risks?

# 4. More information

**Comment by myConsciousness** [comment]
Need to add definition below in `analysis_options.yaml`?

```yaml
analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
```
