### ISSUE TITLE
Add definition in `analysis_options.yaml`

### ISSUE THREAD

**Issue by myConsciousness** [twitter-dart/twitter-api-v2#77]
# 1. What could be improved

```yaml
analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
```

# 2. Why should this be improved

# 3. Any risks?

# 4. More information

#42
